import { z } from 'zod';
import {
  ConsumeOpenKitBootstrapTokenRequestSchema,
  ConsumeOpenKitBootstrapTokenResponseSchema,
  CreateOpenKitAccessTokenRequestSchema,
  CreateOpenKitAccessTokenResponseSchema,
  ListMyAdminAccessTokensResponseSchema,
  ListOpenKitAccessTokensResponseSchema,
  RevokeOpenKitAccessTokenResponseSchema,
  RotateOpenKitAccessTokenRequestSchema,
  RotateOpenKitAccessTokenResponseSchema,
  SetMyAdminAccessTokenDefaultRequestSchema,
  SetMyAdminAccessTokenDefaultResponseSchema,
} from './auth.js';
import type { OperationDefinition } from './operation-contract.js';

/** Human credential lifecycle declarations; bootstrap selects its separate actorless procedure. */
export const ACCESS_TOKEN_OPERATION_DEFINITIONS = {
  'token.my-admin-list': {
    description: 'List owned redacted administrator tokens and the effective default.',
    inputSchema: z.object({}).strict(),
    outputSchema: ListMyAdminAccessTokensResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'user' },
    target: { kind: 'user' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'token.my-admin-default': {
    description: 'Select an owned usable administrator token as the effective default.',
    inputSchema: SetMyAdminAccessTokenDefaultRequestSchema,
    outputSchema: SetMyAdminAccessTokenDefaultResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'user' },
    target: { kind: 'user' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'token.list': {
    description: 'List redacted OpenKit access tokens.',
    inputSchema: z.object({}).strict(),
    outputSchema: ListOpenKitAccessTokensResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'token.create': {
    description: 'Create an OpenKit access token for one-time secret delivery.',
    inputSchema: CreateOpenKitAccessTokenRequestSchema,
    outputSchema: CreateOpenKitAccessTokenResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: true,
    successStatus: 201,
  },
  'token.rotate': {
    description: 'Rotate an OpenKit access token for one-time secret delivery.',
    inputSchema: RotateOpenKitAccessTokenRequestSchema.safeExtend({ tokenId: z.string().min(1) }),
    outputSchema: RotateOpenKitAccessTokenResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: true,
    successStatus: 200,
  },
  'token.revoke': {
    description: 'Revoke one OpenKit access token.',
    inputSchema: z.object({ tokenId: z.string().min(1) }).strict(),
    outputSchema: RevokeOpenKitAccessTokenResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'bootstrap.consume': {
    description:
      'Consume the bootstrap secret to create the login-capable owner and first administrator token.',
    inputSchema: ConsumeOpenKitBootstrapTokenRequestSchema,
    outputSchema: ConsumeOpenKitBootstrapTokenResponseSchema,
    credentials: ['bootstrap-secret'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: true,
    successStatus: 201,
    inputSensitivity: 'secret stdin',
  },
} as const satisfies Record<string, OperationDefinition>;
