import { WorkspaceIdSchema } from '@openkit/protocol';
import { z } from 'zod';
import type { OperationDefinition } from './operation-contract.js';
import {
  CatalogMutationResponseSchema,
  CreateMcpConfigRequestSchema,
  CreateMcpConfigResponseSchema,
  DecideSkillCandidateRequestSchema,
  GetWorkspaceCatalogResponseSchema,
  ImportPluginRequestSchema,
  ImportPluginResponseSchema,
  ImportSkillRequestSchema,
  ImportSkillResponseSchema,
  ListMcpCatalogResponseSchema,
  ListPluginCatalogResponseSchema,
  ListSkillCatalogResponseSchema,
  SelectMcpVersionRequestSchema,
  SelectSkillVersionRequestSchema,
  SkillCandidateResponseSchema,
  SubmitSkillCandidateRequestSchema,
  UpdateMcpBindingRequestSchema,
} from './resource-catalog.js';

/** Public credentials retain current Workspace admission and administrator eligibility. */
const credentials = [
  'local-user',
  'user-session',
  'user-bearer',
  'deployment-administrator',
] as const;

/** Catalog declarations reuse native payloads and closed admission strategies. */
export const CATALOG_OPERATION_DEFINITIONS = {
  'catalog.read': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read the selected Workspace resource catalog.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: GetWorkspaceCatalogResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'catalog.skill-list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List the selected Workspace Skill entries.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListSkillCatalogResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'catalog.skill-import': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 201,
    description: 'Import immutable Skill supply into the selected Workspace.',
    inputSchema: ImportSkillRequestSchema.safeExtend({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ImportSkillResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
  'catalog.skill-candidate-submit': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 201,
    description: 'Submit a Skill candidate against its base digest.',
    inputSchema: SubmitSkillCandidateRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      skillId: z.string().min(1),
    }).strict(),
    outputSchema: SkillCandidateResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
  'catalog.skill-candidate-decide': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Decide a Skill candidate with catalog revision admission.',
    inputSchema: DecideSkillCandidateRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      candidateId: z.string().min(1),
    }).strict(),
    outputSchema: CatalogMutationResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
  'catalog.skill-select': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Select the default immutable Skill version.',
    inputSchema: SelectSkillVersionRequestSchema.safeExtend({
      digest: SelectSkillVersionRequestSchema.shape.digest.unwrap(),
      workspaceId: WorkspaceIdSchema,
      skillId: z.string().min(1),
    }).strict(),
    outputSchema: CatalogMutationResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
  'catalog.skill-pin': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Set or remove an immutable Skill pin.',
    inputSchema: SelectSkillVersionRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      skillId: z.string().min(1),
    }).strict(),
    outputSchema: CatalogMutationResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
  'catalog.mcp-list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List redacted MCP catalog entries.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListMcpCatalogResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'catalog.mcp-create': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 201,
    description: 'Create and select immutable MCP configuration supply.',
    inputSchema: CreateMcpConfigRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
    }).strict(),
    outputSchema: CreateMcpConfigResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
  'catalog.mcp-select': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Select an immutable MCP configuration version.',
    inputSchema: SelectMcpVersionRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      mcpId: z.string().min(1),
    }).strict(),
    outputSchema: CatalogMutationResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
  'catalog.mcp-binding': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Update the selected MCP binding without disclosing credentials.',
    inputSchema: UpdateMcpBindingRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      mcpId: z.string().min(1),
    }).strict(),
    outputSchema: CatalogMutationResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
  'catalog.plugin-list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List installed Agent Plugin entries.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListPluginCatalogResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'catalog.plugin-import': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 201,
    description: 'Import immutable Agent Plugin supply.',
    inputSchema: ImportPluginRequestSchema.safeExtend({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ImportPluginResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
} as const satisfies Record<string, OperationDefinition>;
