import { RequestIdSchema, WorkspaceIdSchema } from '@openkit/protocol';
import { z } from 'zod';
import {
  GenerativePresentationDataModelResponseSchema,
  GenerativePresentationResourceResponseSchema,
  GetGenerativePresentationResponseSchema,
  PublishGenerativePresentationRequestSchema,
  PublishGenerativePresentationResponseSchema,
  RefreshGenerativePresentationRequestSchema,
  SubmitGenerativePresentationActionRequestSchema,
} from './generative-ui.js';
import {
  CreateLightAppRequestSchema,
  CreateLightAppResponseSchema,
  GetLightAppRecordResponseSchema,
  LightAppBatchRequestSchema,
  LightAppBatchResponseSchema,
  ListLightAppRecordsResponseSchema,
  ListLightAppsResponseSchema,
  RetireLightAppRequestSchema,
  RetireLightAppResponseSchema,
  UpdateLightAppRecordRequestSchema,
  UpdateLightAppRecordResponseSchema,
  UpdateLightAppSchemaRequestSchema,
  UpdateLightAppSchemaResponseSchema,
} from './light-apps.js';
import type { OperationDefinition } from './operation-contract.js';

const credentials = [
  'local-user',
  'user-session',
  'user-bearer',
  'deployment-administrator',
  'worker-package',
] as const;
const workspace = { workspaceId: WorkspaceIdSchema };
const app = { ...workspace, appId: z.string().uuid() };
const collection = { ...app, collection: z.string().min(1) };
const record = { ...collection, recordId: z.string().uuid() };
const presentation = { ...workspace, presentationId: z.string().uuid() };
const revision = z.number().int().positive();
const paging = { page: revision.optional(), perPage: revision.max(100).optional() };

/** Release-authored definitions for the existing remaining Kernel operations; effects remain with NanoCore owners. */
export const KERNEL_REMAINING_OPERATION_DEFINITIONS = {
  'kernel.apps.list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List Light Apps in the current Workspace.',
    inputSchema: z.object({ ...workspace, ...paging }).strict(),
    outputSchema: ListLightAppsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'kernel.apps.create': {
    binding: 'json',
    returnsOneTimeSecret: false,
    description: 'Create one Light App from a file-authored schema.',
    inputSchema: CreateLightAppRequestSchema.safeExtend({
      ...workspace,
      requestId: RequestIdSchema,
    }),
    outputSchema: CreateLightAppResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
    successStatus: 201,
  },
  'kernel.schema.update': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Update one Light App schema within the initial evolution ceiling.',
    inputSchema: UpdateLightAppSchemaRequestSchema.extend({ ...app, requestId: RequestIdSchema }),
    outputSchema: UpdateLightAppSchemaResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-light-app', field: 'appId' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
  'kernel.apps.retire': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Retire one Light App and disable writes.',
    inputSchema: RetireLightAppRequestSchema.extend({ ...app, requestId: RequestIdSchema }),
    outputSchema: RetireLightAppResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-light-app', field: 'appId' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
  'kernel.records.list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List records in one Light App collection.',
    inputSchema: z
      .object({
        ...collection,
        schemaRevision: revision,
        ...paging,
        filter: z.string().optional(),
        sort: z.string().optional(),
        fields: z.string().optional(),
      })
      .strict(),
    outputSchema: ListLightAppRecordsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-light-app', field: 'appId' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'kernel.records.get': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read one Light App record.',
    inputSchema: z
      .object({ ...record, schemaRevision: revision, fields: z.string().optional() })
      .strict(),
    outputSchema: GetLightAppRecordResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-light-app', field: 'appId' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'kernel.records.update': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Update one Light App record.',
    inputSchema: UpdateLightAppRecordRequestSchema.extend({
      ...record,
      requestId: RequestIdSchema,
    }),
    outputSchema: UpdateLightAppRecordResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-light-app', field: 'appId' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
  'kernel.records.batch': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Apply one atomic Light App record batch.',
    inputSchema: LightAppBatchRequestSchema.extend({ ...app, requestId: RequestIdSchema }),
    outputSchema: LightAppBatchResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-light-app', field: 'appId' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
} as const satisfies Record<string, OperationDefinition>;

/** Release-authored definitions for the existing Generative UI operations; effects remain with NanoCore owners. */
export const GENERATIVE_UI_OPERATION_DEFINITIONS = {
  'generative-ui.publish': {
    binding: 'json',
    returnsOneTimeSecret: false,
    description: 'Publish one admitted native Generative UI presentation.',
    inputSchema: PublishGenerativePresentationRequestSchema.extend({
      ...workspace,
      requestId: RequestIdSchema,
    }),
    outputSchema: PublishGenerativePresentationResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.write',
    mutating: true,
    successStatus: 201,
  },
  'generative-ui.get': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read one retained Generative UI presentation.',
    inputSchema: z.object(presentation).strict(),
    outputSchema: GetGenerativePresentationResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'thread.read',
    mutating: false,
  },
  'generative-ui.resource': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read the retained native A2UI resource for one presentation.',
    inputSchema: z.object(presentation).strict(),
    outputSchema: GenerativePresentationResourceResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'thread.read',
    mutating: false,
  },
  'generative-ui.refresh': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Refresh one presentation from its current authorized source.',
    inputSchema: RefreshGenerativePresentationRequestSchema.extend(presentation),
    outputSchema: GenerativePresentationDataModelResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'thread.read',
    mutating: false,
  },
  'generative-ui.action': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Submit one admitted Kernel record-update action.',
    inputSchema: SubmitGenerativePresentationActionRequestSchema.extend({
      ...presentation,
      requestId: RequestIdSchema,
    }),
    outputSchema: GenerativePresentationDataModelResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
} as const satisfies Record<string, OperationDefinition>;
