import {
  CreateKnowledgeEntryRequestSchema,
  DeleteKnowledgeEntryRequestSchema,
  KnowledgeEntrySchema,
  ListKnowledgeEntriesResponseSchema,
  UpdateKnowledgeEntryRequestSchema,
  WorkspaceIdSchema,
} from '@openkit/protocol';
import { z } from 'zod';
import {
  ReverseKnowledgeProposalRequestSchema,
  ReverseKnowledgeProposalResponseSchema,
  SubmitKnowledgeProposalDecisionRequestSchema,
  SubmitKnowledgeProposalDecisionResponseSchema,
} from './action-center.js';
import {
  KnowledgeDerivedIndexesResponseSchema,
  KnowledgeManagerAnswerRequestSchema,
  KnowledgeManagerAnswerResponseSchema,
  KnowledgeManagerDraftProposalRequestSchema,
  KnowledgeManagerDraftProposalResponseSchema,
  KnowledgeManagerHealthCheckRequestSchema,
  KnowledgeManagerHealthCheckResponseSchema,
  KnowledgeManagerPrepareContextRequestSchema,
  KnowledgeManagerPrepareContextResponseSchema,
  KnowledgeManagerSuggestRepairRequestSchema,
  KnowledgeManagerSuggestRepairResponseSchema,
  KnowledgeRetrievalResponseSchema,
  ListKnowledgeClaimsResponseSchema,
  ListKnowledgeConflictsResponseSchema,
  ListKnowledgeObservationsResponseSchema,
  ListKnowledgeSourcesResponseSchema,
  ReadKnowledgeSourceResponseSchema,
  RecordKnowledgeClaimRequestSchema,
  RecordKnowledgeClaimResponseSchema,
  RecordKnowledgeConflictRequestSchema,
  RecordKnowledgeConflictResponseSchema,
  RecordKnowledgeObservationRequestSchema,
  RecordKnowledgeObservationResponseSchema,
  RegisterKnowledgeSourceRequestSchema,
  RegisterKnowledgeSourceResponseSchema,
  ResolveKnowledgeConflictRequestSchema,
  ResolveKnowledgeConflictResponseSchema,
  RetrieveKnowledgeRequestSchema,
} from './knowledge-manager.js';
import type { OperationDefinition } from './operation-contract.js';

/** Credentials already used by the public Workspace, Thread and Turn families. */
const publicCredentials = [
  'local-user',
  'user-session',
  'user-bearer',
  'deployment-administrator',
] as const;

const workspaceSelector = { workspaceId: WorkspaceIdSchema };

/** Sole public contracts for the governed Knowledge family, including its request-scoped Manager views. */
export const KNOWLEDGE_OPERATION_DEFINITIONS = {
  'knowledge.answer': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Answer one bounded question from governed Workspace Knowledge.',
    inputSchema: KnowledgeManagerAnswerRequestSchema.extend({ ...workspaceSelector }).strict(),
    outputSchema: KnowledgeManagerAnswerResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.source.list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List registered Workspace Knowledge Sources.',
    inputSchema: z.object({ ...workspaceSelector }).strict(),
    outputSchema: ListKnowledgeSourcesResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.source.register': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Register one explicit Knowledge Source and captured text material.',
    inputSchema: RegisterKnowledgeSourceRequestSchema.extend({ ...workspaceSelector }).strict(),
    outputSchema: RegisterKnowledgeSourceResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.write',
    mutating: true,
  },
  'knowledge.source.read': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read one scoped Knowledge Source and its derived metadata.',
    inputSchema: z.object({ ...workspaceSelector, sourceId: z.string().min(1) }).strict(),
    outputSchema: ReadKnowledgeSourceResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.observation.list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List retained Knowledge maintenance observations.',
    inputSchema: z.object({ ...workspaceSelector }).strict(),
    outputSchema: ListKnowledgeObservationsResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.observation.record': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Record one Knowledge maintenance observation.',
    inputSchema: RecordKnowledgeObservationRequestSchema.extend({ ...workspaceSelector }).strict(),
    outputSchema: RecordKnowledgeObservationResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.write',
    mutating: true,
  },
  'knowledge.claim.list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List Knowledge maintenance claims.',
    inputSchema: z.object({ ...workspaceSelector }).strict(),
    outputSchema: ListKnowledgeClaimsResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.claim.record': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Record one Knowledge maintenance claim.',
    inputSchema: RecordKnowledgeClaimRequestSchema.extend({ ...workspaceSelector }).strict(),
    outputSchema: RecordKnowledgeClaimResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.write',
    mutating: true,
  },
  'knowledge.conflict.list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List the latest Knowledge conflict maintenance records.',
    inputSchema: z.object({ ...workspaceSelector }).strict(),
    outputSchema: ListKnowledgeConflictsResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.conflict.record': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Record one Knowledge conflict without publishing content.',
    inputSchema: RecordKnowledgeConflictRequestSchema.extend({ ...workspaceSelector }).strict(),
    outputSchema: RecordKnowledgeConflictResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.write',
    mutating: true,
  },
  'knowledge.conflict.resolve': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Resolve one scoped Knowledge conflict.',
    inputSchema: ResolveKnowledgeConflictRequestSchema.extend({
      ...workspaceSelector,
      conflictId: z.string().min(1),
    }).strict(),
    outputSchema: ResolveKnowledgeConflictResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.write',
    mutating: true,
  },
  'knowledge.indexes': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read rebuildable Knowledge indexes from their file-backed owner.',
    inputSchema: z.object({ ...workspaceSelector }).strict(),
    outputSchema: KnowledgeDerivedIndexesResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.retrieval': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Retrieve governed Knowledge candidates and record their selection trace.',
    inputSchema: RetrieveKnowledgeRequestSchema.extend({ ...workspaceSelector }).strict(),
    outputSchema: KnowledgeRetrievalResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: true,
  },
  'knowledge.context.prepare': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Prepare bounded Knowledge selection material and its existing retrieval trace.',
    inputSchema: KnowledgeManagerPrepareContextRequestSchema.extend({
      ...workspaceSelector,
    }).strict(),
    outputSchema: KnowledgeManagerPrepareContextResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: true,
  },
  'knowledge.proposal.draft': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Draft one pending source-verified Knowledge Proposal.',
    inputSchema: KnowledgeManagerDraftProposalRequestSchema.extend({
      ...workspaceSelector,
    }).strict(),
    outputSchema: KnowledgeManagerDraftProposalResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.propose',
    mutating: true,
  },
  'knowledge.repair.suggest': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Suggest bounded review-required repairs without applying them.',
    inputSchema: KnowledgeManagerSuggestRepairRequestSchema.extend({
      ...workspaceSelector,
    }).strict(),
    outputSchema: KnowledgeManagerSuggestRepairResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.health.check': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Inspect Knowledge health without applying or scheduling work.',
    inputSchema: KnowledgeManagerHealthCheckRequestSchema.extend({ ...workspaceSelector }).strict(),
    outputSchema: KnowledgeManagerHealthCheckResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.proposal.decide': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Decide one fixed Knowledge Proposal through its review and publication owner.',
    inputSchema: SubmitKnowledgeProposalDecisionRequestSchema.extend({
      ...workspaceSelector,
      proposalId: z.string().min(1),
    }).strict(),
    outputSchema: SubmitKnowledgeProposalDecisionResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'review.apply',
    mutating: true,
  },
  'knowledge.proposal.reverse': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Reverse the unchanged page application of one accepted Knowledge Proposal.',
    inputSchema: ReverseKnowledgeProposalRequestSchema.extend({
      ...workspaceSelector,
      proposalId: z.string().min(1),
    }).strict(),
    outputSchema: ReverseKnowledgeProposalResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.write',
    mutating: true,
  },
} as const satisfies Record<string, OperationDefinition>;

/** Sole public contracts for the retained minimal Knowledge Entry family; records stay with the protocol owner. */
export const KNOWLEDGE_ENTRY_OPERATION_DEFINITIONS = {
  'knowledge.list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List retained Workspace Knowledge Entries.',
    inputSchema: z.object({ ...workspaceSelector }).strict(),
    outputSchema: ListKnowledgeEntriesResponseSchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.read',
    mutating: false,
  },
  'knowledge.create': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Create one validated Workspace Knowledge Entry.',
    inputSchema: CreateKnowledgeEntryRequestSchema.extend({ ...workspaceSelector }).strict(),
    outputSchema: KnowledgeEntrySchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.write',
    mutating: true,
  },
  'knowledge.update': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Update one scoped Workspace Knowledge Entry.',
    inputSchema: UpdateKnowledgeEntryRequestSchema.extend({
      ...workspaceSelector,
      knowledgeEntryId: z.string().min(1),
    }).strict(),
    outputSchema: KnowledgeEntrySchema,
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.write',
    mutating: true,
  },
  'knowledge.delete': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Delete one scoped Workspace Knowledge Entry.',
    inputSchema: DeleteKnowledgeEntryRequestSchema.extend({
      ...workspaceSelector,
      knowledgeEntryId: z.string().min(1),
    }).strict(),
    outputSchema: z.null(),
    credentials: publicCredentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'knowledge.write',
    mutating: true,
  },
} as const satisfies Record<string, OperationDefinition>;
