import { z } from 'zod';
import {
  BindThreadMaterialRequestSchema,
  BindThreadMaterialResponseSchema,
  CreateWorkspaceMaterialRequestSchema,
  CreateWorkspaceMaterialResponseSchema,
  ExcludeThreadMaterialRequestSchema,
  ExcludeThreadMaterialResponseSchema,
  GetThreadMaterialResponseSchema,
  GetWorkspaceMaterialResponseSchema,
  GetWorkspaceMaterialRevisionResponseSchema,
  ListWorkspaceMaterialRevisionsResponseSchema,
  ListWorkspaceMaterialsResponseSchema,
  RestoreThreadMaterialRequestSchema,
  RestoreThreadMaterialResponseSchema,
  SaveWorkspaceMaterialRevisionRequestSchema,
  SaveWorkspaceMaterialRevisionResponseSchema,
  UnbindThreadMaterialRequestSchema,
  UnbindThreadMaterialResponseSchema,
} from './material.js';
import type { OperationDefinition } from './operation-contract.js';

const opaqueId = z.string().min(1);
const workspace = { workspaceId: opaqueId };
const credentials = [
  'local-user',
  'user-session',
  'user-bearer',
  'deployment-administrator',
] as const;

/** Material definitions preserve metadata, exact revisions and singular Thread binding commands. */
export const MATERIAL_OPERATION_DEFINITIONS = {
  'material.list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List Workspace Material metadata.',
    inputSchema: z.object({ ...workspace }).strict(),
    outputSchema: ListWorkspaceMaterialsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'material.create': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 201,
    description: 'Create one Workspace Material.',
    inputSchema: CreateWorkspaceMaterialRequestSchema.extend({ ...workspace }).strict(),
    outputSchema: CreateWorkspaceMaterialResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
  'material.read': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read one Workspace Material metadata record.',
    inputSchema: z.object({ ...workspace, materialId: opaqueId }).strict(),
    outputSchema: GetWorkspaceMaterialResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'material.revision-list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List immutable Workspace Material revision metadata.',
    inputSchema: z.object({ ...workspace, materialId: opaqueId }).strict(),
    outputSchema: ListWorkspaceMaterialRevisionsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'material.revision-save': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 201,
    description: 'Save one immutable Workspace Material revision.',
    inputSchema: SaveWorkspaceMaterialRevisionRequestSchema.extend({
      ...workspace,
      materialId: opaqueId,
    }).strict(),
    outputSchema: SaveWorkspaceMaterialRevisionResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
  'material.revision-read': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read one exact Workspace Material revision.',
    inputSchema: z.object({ ...workspace, materialId: opaqueId, revisionId: opaqueId }).strict(),
    outputSchema: GetWorkspaceMaterialRevisionResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'material.thread-read': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read the singular Thread Material projection.',
    inputSchema: z.object({ ...workspace, threadId: opaqueId }).strict(),
    outputSchema: GetThreadMaterialResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'addressed-thread', threadField: 'threadId', missing: 'not-found' },
    policyOperation: 'thread.read',
    mutating: false,
  },
  'material.bind': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Bind one Workspace Material to a Thread.',
    inputSchema: BindThreadMaterialRequestSchema.extend({
      ...workspace,
      threadId: opaqueId,
      materialId: opaqueId,
    }).strict(),
    outputSchema: BindThreadMaterialResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'addressed-thread', threadField: 'threadId', missing: 'not-found' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
  'material.unbind': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Unbind one Workspace Material from a Thread.',
    inputSchema: UnbindThreadMaterialRequestSchema.extend({
      ...workspace,
      threadId: opaqueId,
      materialId: opaqueId,
    }).strict(),
    outputSchema: UnbindThreadMaterialResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'addressed-thread', threadField: 'threadId', missing: 'not-found' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
  'material.exclude': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Exclude one bound Workspace Material from worker context.',
    inputSchema: ExcludeThreadMaterialRequestSchema.extend({
      ...workspace,
      threadId: opaqueId,
      materialId: opaqueId,
    }).strict(),
    outputSchema: ExcludeThreadMaterialResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'addressed-thread', threadField: 'threadId', missing: 'not-found' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
  'material.restore': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Restore one bound Workspace Material to worker context.',
    inputSchema: RestoreThreadMaterialRequestSchema.extend({
      ...workspace,
      threadId: opaqueId,
      materialId: opaqueId,
    }).strict(),
    outputSchema: RestoreThreadMaterialResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'addressed-thread', threadField: 'threadId', missing: 'not-found' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
} as const satisfies Record<string, OperationDefinition>;
