import { z } from 'zod';
import type { OperationDefinition } from './operation-contract.js';
import {
  CancelProviderSubscriptionAccountLoginRequestSchema,
  CreateProviderSubscriptionAccountRequestSchema,
  ProviderSubscriptionAccountSchema,
  ProviderSubscriptionAccountsResponseSchema,
  ProviderSubscriptionAutoTopupSchema,
  ProviderSubscriptionQuotaSchema,
  ProviderSubscriptionsResponseSchema,
  StartProviderSubscriptionAccountLoginRequestSchema,
  UpdateProviderSubscriptionAccountRequestSchema,
} from './provider-subscriptions.js';

// Selector validity stays with the account owner so unsupported providers retain 404 and malformed slots retain their specific 400.
const providerSelector = { subscriptionProviderId: z.string() };
const pairSelector = { ...providerSelector, accountSlotId: z.string() };

/** Generic provider-slot operations join the existing subscription account and observation owners. */
export const PROVIDER_SUBSCRIPTION_OPERATION_DEFINITIONS = {
  'provider-subscription.provider-list': {
    description: 'List supported provider subscriptions.',
    inputSchema: z.object({}).strict(),
    outputSchema: ProviderSubscriptionsResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'provider-subscription.account-list': {
    description: 'List provider-subscription account slots.',
    inputSchema: z.object(providerSelector).strict(),
    outputSchema: ProviderSubscriptionAccountsResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'provider-subscription.account-create': {
    description: 'Create one provider-subscription account slot.',
    inputSchema: CreateProviderSubscriptionAccountRequestSchema.extend(providerSelector),
    outputSchema: ProviderSubscriptionAccountSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'provider-subscription.account-update': {
    description: 'Update one provider-subscription account slot.',
    inputSchema: UpdateProviderSubscriptionAccountRequestSchema.extend(pairSelector),
    outputSchema: ProviderSubscriptionAccountSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'provider-subscription.account-delete': {
    description: 'Delete one provider-subscription account slot.',
    inputSchema: z.object(pairSelector).strict(),
    outputSchema: z.null(),
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 204,
  },
  'provider-subscription.account-status': {
    description: 'Read the sanitized status of one provider-subscription account.',
    inputSchema: z.object(pairSelector).strict(),
    outputSchema: ProviderSubscriptionAccountSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'provider-subscription.account-login-start': {
    description: 'Start device-code login for one provider-subscription account.',
    inputSchema: StartProviderSubscriptionAccountLoginRequestSchema.extend(pairSelector),
    outputSchema: ProviderSubscriptionAccountSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'provider-subscription.account-login-cancel': {
    description: 'Cancel one exact provider-subscription login interaction.',
    inputSchema: CancelProviderSubscriptionAccountLoginRequestSchema.extend(pairSelector),
    outputSchema: ProviderSubscriptionAccountSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'provider-subscription.account-logout': {
    description: 'Log out one provider-subscription account.',
    inputSchema: z.object(pairSelector).strict(),
    outputSchema: ProviderSubscriptionAccountSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'provider-subscription.account-quota': {
    description: 'Read bounded provider-subscription quota observations.',
    inputSchema: z.object(pairSelector).strict(),
    outputSchema: ProviderSubscriptionQuotaSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'provider-subscription.account-auto-topup': {
    description: 'Read the supported provider-subscription auto-top-up observation.',
    inputSchema: z.object(pairSelector).strict(),
    outputSchema: ProviderSubscriptionAutoTopupSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
} as const satisfies Record<string, OperationDefinition>;
