import { z } from 'zod';
import type { OperationDefinition } from './operation-contract.js';
import {
  AgentNativeEnvironmentResponseSchema,
  RuntimeConfigFileDeleteRequestSchema,
  RuntimeConfigFileListResponseSchema,
  RuntimeConfigFileReadResponseSchema,
  RuntimeConfigFileWriteRequestSchema,
  RuntimeConfigFileWriteResponseSchema,
  RuntimeConfigReloadRequestSchema,
  RuntimeConfigReloadResponseSchema,
  RuntimeConfigSchemaCatalogResponseSchema,
  RuntimeConfigValidationRequestSchema,
  RuntimeConfigValidationResponseSchema,
  UpdateAgentNativeEnvironmentRequestSchema,
} from './runtime-config.js';

/** Deployment administrator configuration commands retain their native CAS and reload owners. */
export const RUNTIME_CONFIG_OPERATION_DEFINITIONS = {
  'runtime.agent-environment-read': {
    description:
      'Read admitted Agent environment defaults, overrides and native application status.',
    inputSchema: z.object({ fileId: z.string().min(1) }).strict(),
    outputSchema: AgentNativeEnvironmentResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'runtime.agent-environment-update': {
    description: 'Edit Agent environment overrides against exact file and image evidence.',
    inputSchema: UpdateAgentNativeEnvironmentRequestSchema,
    outputSchema: AgentNativeEnvironmentResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'runtime.reload': {
    description: 'Reload supported runtime configuration.',
    inputSchema: RuntimeConfigReloadRequestSchema,
    outputSchema: RuntimeConfigReloadResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'runtime.file-list': {
    description: 'List editable runtime configuration files.',
    inputSchema: z.object({}).strict(),
    outputSchema: RuntimeConfigFileListResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'runtime.file-read': {
    description: 'Read one runtime configuration file.',
    inputSchema: z.object({ id: z.string().min(1) }).strict(),
    outputSchema: RuntimeConfigFileReadResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    invalidInputCode: 'missing_config_file_id',
  },
  'runtime.file-create': {
    description: 'Create one supported runtime configuration file.',
    inputSchema: RuntimeConfigFileWriteRequestSchema,
    outputSchema: RuntimeConfigFileWriteResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'runtime.file-update': {
    description: 'Update one runtime configuration file with exact revision protection.',
    inputSchema: RuntimeConfigFileWriteRequestSchema,
    outputSchema: RuntimeConfigFileWriteResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'runtime.file-delete': {
    description: 'Delete one exact Provider profile and revoke its key reference.',
    inputSchema: RuntimeConfigFileDeleteRequestSchema,
    outputSchema: z.null(),
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 204,
  },
  'runtime.schemas': {
    description: 'Read runtime configuration schemas.',
    inputSchema: z.object({}).strict(),
    outputSchema: RuntimeConfigSchemaCatalogResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
  'runtime.validate': {
    description: 'Validate runtime configuration without writing it.',
    inputSchema: RuntimeConfigValidationRequestSchema,
    outputSchema: RuntimeConfigValidationResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
  },
} as const satisfies Record<string, OperationDefinition>;
