import { WorkspaceIdSchema } from '@openkit/protocol';
import { z } from 'zod';
import {
  GetWorkspaceApplyResultResponseSchema,
  GetWorkspaceSyncReviewResponseSchema,
  ListBackendWorkspaceHandlesResponseSchema,
  ListStagedWorkspaceReviewsResponseSchema,
  ListWorkerOutputManifestsResponseSchema,
  ListWorkspaceApplyPlansResponseSchema,
  ListWorkspaceApplyResultsResponseSchema,
  ListWorkspaceChangeSetsResponseSchema,
  ListWorkspaceInputSnapshotsResponseSchema,
  ListWorkspaceMaterializationRecordsResponseSchema,
  ListWorkspaceQuarantineRecordsResponseSchema,
  ListWorkspaceReconciliationRecordsResponseSchema,
  ListWorkspaceSyncReviewsResponseSchema,
  SubmitWorkspaceRecoveryDecisionRequestSchema,
  SubmitWorkspaceRecoveryDecisionResponseSchema,
  SubmitWorkspaceSyncReviewDecisionRequestSchema,
  SubmitWorkspaceSyncReviewDecisionResponseSchema,
} from './workspace-sync.js';

const credentials = [
  'local-user',
  'user-session',
  'user-bearer',
  'deployment-administrator',
] as const;

/** Sole public contract for the existing non-Git synchronization operations. Decision identities keep the owner's nonempty string schema so retained non-UUID receipts remain replayable. */
export const SYNC_OPERATION_DEFINITIONS = {
  'sync.review-list': {
    description: 'Review list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceSyncReviewsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.review-read': {
    description: 'Review read for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema, reviewId: z.string().min(1) }).strict(),
    outputSchema: GetWorkspaceSyncReviewResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.review-decide': {
    description: 'Review decide for one Workspace.',
    inputSchema: SubmitWorkspaceSyncReviewDecisionRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      reviewId: z.string().min(1),
      requestId: SubmitWorkspaceSyncReviewDecisionRequestSchema.shape.requestId.unwrap(),
    }),
    outputSchema: SubmitWorkspaceSyncReviewDecisionResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'review.apply',
    mutating: true,
  },
  'sync.input-snapshot-list': {
    description: 'Input snapshot list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceInputSnapshotsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.materialization-list': {
    description: 'Materialization list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceMaterializationRecordsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.backend-handle-list': {
    description: 'Backend handle list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListBackendWorkspaceHandlesResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'audit.read',
    mutating: false,
  },
  'sync.output-manifest-list': {
    description: 'Output manifest list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkerOutputManifestsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.change-set-list': {
    description: 'Change set list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceChangeSetsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.staged-review-list': {
    description: 'Staged review list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListStagedWorkspaceReviewsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.apply-result-list': {
    description: 'Apply result list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceApplyResultsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.apply-plan-list': {
    description: 'Apply plan list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceApplyPlansResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.reconciliation-list': {
    description: 'Reconciliation list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceReconciliationRecordsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.recovery-decide': {
    description: 'Recovery decide for one Workspace.',
    inputSchema: SubmitWorkspaceRecoveryDecisionRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      reconciliationRecordId: z.string().min(1),
      requestId: SubmitWorkspaceRecoveryDecisionRequestSchema.shape.requestId.unwrap(),
    }),
    outputSchema: SubmitWorkspaceRecoveryDecisionResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'review.apply',
    mutating: true,
  },
  'sync.quarantine-list': {
    description: 'Quarantine list for one Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceQuarantineRecordsResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'sync.apply-result-read': {
    description: 'Apply result read for one Workspace.',
    inputSchema: z
      .object({ workspaceId: WorkspaceIdSchema, applyResultId: z.string().min(1) })
      .strict(),
    outputSchema: GetWorkspaceApplyResultResponseSchema,
    credentials,
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
} as const;
