import { WorkspaceIdSchema } from '@openkit/protocol';
import { z } from 'zod';
import type { OperationDefinition } from './operation-contract.js';
import {
  CreateWorkspaceVaultGrantRequestSchema,
  CreateWorkspaceVaultSecretRequestSchema,
  RotateWorkspaceVaultSecretRequestSchema,
  SetProviderApiKeyRequestSchema,
  SetProviderApiKeyResponseSchema,
  VaultAdminBootstrapCodexAuthJsonRequestSchema,
  VaultAdminBootstrapCodexAuthJsonResponseSchema,
  VaultAdminListWorkspaceReferencesResponseSchema,
  VaultAdminLockResponseSchema,
  VaultAdminRebindWorkspaceReferenceRequestSchema,
  VaultAdminRebindWorkspaceReferenceResponseSchema,
  VaultAdminStatusResponseSchema,
  VaultAdminUnlockRequestSchema,
  VaultAdminUnlockResponseSchema,
  VaultAdminWorkspaceReferenceSchema,
} from './vault-admin.js';
import {
  ListWorkspaceVaultGrantsResponseSchema,
  ListWorkspaceVaultInjectionPlansResponseSchema,
  ListWorkspaceVaultInjectionReceiptsResponseSchema,
  WorkspaceVaultGrantSchema,
} from './vault-injection.js';
import {
  ListServerVaultUseRecordsResponseSchema,
  ListWorkspaceVaultUseRecordsResponseSchema,
} from './vault-use.js';

/** Complete Vault contracts expose redacted metadata and request-only sensitive material. */
export const VAULT_OPERATION_DEFINITIONS = {
  'vault.status': {
    description: 'Read redacted vault administration status.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z.object({}).strict(),
    outputSchema: VaultAdminStatusResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
  },
  'vault.unlock': {
    description: 'Unlock the configured vault backend.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: VaultAdminUnlockRequestSchema.strict(),
    outputSchema: VaultAdminUnlockResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    inputSensitivity: 'secret stdin',
  },
  'vault.lock': {
    description: 'Lock the configured vault backend.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z.object({}).strict(),
    outputSchema: VaultAdminLockResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
  },
  'vault.bootstrap-codex-auth': {
    description: 'Store Codex authentication material in the unlocked vault.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: VaultAdminBootstrapCodexAuthJsonRequestSchema.strict(),
    outputSchema: VaultAdminBootstrapCodexAuthJsonResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    inputSensitivity: 'secret stdin',
  },
  // The native owner validates the profile id with ProviderApiKeyProfileIdSchema so its exact typed refusal and audited no-write outcome stay reachable.
  'vault.provider-api-key-set': {
    description: 'Store or replace one provider profile API key in the unlocked vault.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: SetProviderApiKeyRequestSchema.safeExtend({
      providerId: z.string().min(1),
    }).strict(),
    outputSchema: SetProviderApiKeyResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: true,
    inputSensitivity: 'secret stdin',
  },
  'vault.secret-create': {
    description:
      'Secret create for a workspace; gateway-only grants have no capability target and serve selected MCP under existing authority; runtime-env github-token is the separate user-space path.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: CreateWorkspaceVaultSecretRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
    }).strict(),
    outputSchema: VaultAdminWorkspaceReferenceSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: true,
    inputSensitivity: 'secret stdin',
  },
  'vault.secret-rotate': {
    description:
      'Secret rotate for a workspace; gateway-only grants have no capability target and serve selected MCP under existing authority; runtime-env github-token is the separate user-space path.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: RotateWorkspaceVaultSecretRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      referenceId: z.string().min(1),
    }).strict(),
    outputSchema: VaultAdminWorkspaceReferenceSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: true,
    inputSensitivity: 'secret stdin',
  },
  'vault.secret-revoke': {
    description:
      'Secret revoke for a workspace; gateway-only grants have no capability target and serve selected MCP under existing authority; runtime-env github-token is the separate user-space path.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z
      .object({ workspaceId: WorkspaceIdSchema, referenceId: z.string().min(1) })
      .strict(),
    outputSchema: VaultAdminWorkspaceReferenceSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: true,
  },
  'vault.grant-create': {
    description:
      'Create an ordinary gateway-only workspace grant with no capability target for selected MCP under existing authority, or a separate user-space runtime-env github-token grant.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: CreateWorkspaceVaultGrantRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
    }).strict(),
    outputSchema: WorkspaceVaultGrantSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: true,
  },
  'vault.grant-revoke': {
    description:
      'Grant revoke for a workspace; gateway-only grants have no capability target and serve selected MCP under existing authority; runtime-env github-token is the separate user-space path.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema, grantId: z.string().min(1) }).strict(),
    outputSchema: WorkspaceVaultGrantSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: true,
  },
  'vault.reference-rebind': {
    description: 'Rebind one imported workspace vault reference.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: VaultAdminRebindWorkspaceReferenceRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      referenceId: z.string().min(1),
    }).strict(),
    outputSchema: VaultAdminRebindWorkspaceReferenceResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: true,
    inputSensitivity: 'secret stdin',
  },
  'vault.reference-list': {
    description: 'List redacted vault references for one workspace.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: VaultAdminListWorkspaceReferencesResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: false,
  },
  'vault.grant-list': {
    description: 'List non-secret vault grants for one workspace.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceVaultGrantsResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: false,
  },
  'vault.injection-plan-list': {
    description: 'List non-secret vault injection plans for one workspace.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceVaultInjectionPlansResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: false,
  },
  'vault.injection-receipt-list': {
    description: 'List non-secret vault injection receipts for one workspace.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceVaultInjectionReceiptsResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'vault.admin',
    mutating: false,
  },
  'vault.use-list': {
    description: 'List redacted vault use records for one workspace.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceVaultUseRecordsResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'audit.read',
    mutating: false,
  },
  'vault.server-use-list': {
    description: 'List redacted server vault use records.',
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    inputSchema: z.object({}).strict(),
    outputSchema: ListServerVaultUseRecordsResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'server' },
    policyOperation: 'api.call',
    mutating: false,
  },
} as const satisfies Record<string, OperationDefinition>;
