import { WorkspaceIdSchema } from '@openkit/protocol';
import { z } from 'zod';
import type { OperationDefinition } from './operation-contract.js';
import {
  ActivateWorkerEnvironmentRequestSchema,
  ActivateWorkerEnvironmentResponseSchema,
  GetWorkerEnvironmentStatusResponseSchema,
  ListWorkerEnvironmentsQuerySchema,
  ListWorkerEnvironmentsResponseSchema,
  PrepareWorkerEnvironmentResponseSchema,
  PurgeWorkerEnvironmentRequestSchema,
  PurgeWorkerEnvironmentResponseSchema,
  SelectWorkerEnvironmentRequestSchema,
  SelectWorkerEnvironmentResponseSchema,
  WorkerEnvironmentPrepareInputSchema,
  WorkerEnvironmentRecoverInputSchema,
  WorkerEnvironmentStorageRefSchema,
} from './worker-environment.js';

const workspaceSelector = { workspaceId: WorkspaceIdSchema };
/** Release-authored family facts; authority, replay and effects remain with their native owners. */
export const WORKER_ENVIRONMENT_OPERATION_DEFINITIONS = {
  'worker-environment.list': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'List currently authorized retained Worker environments.',
    inputSchema: ListWorkerEnvironmentsQuerySchema.safeExtend(workspaceSelector),
    outputSchema: ListWorkerEnvironmentsResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'worker-environment.select': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Recheck one explicit Worker environment selection without reserving it.',
    inputSchema: SelectWorkerEnvironmentRequestSchema.safeExtend(workspaceSelector),
    outputSchema: SelectWorkerEnvironmentResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'worker-environment.status': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Read current Core and host facts for one retained Worker environment.',
    inputSchema: z
      .object({ ...workspaceSelector, storageRef: WorkerEnvironmentStorageRefSchema })
      .strict(),
    outputSchema: GetWorkerEnvironmentStatusResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.read',
    mutating: false,
  },
  'worker-environment.purge': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Purge one exact idle environment under payload-bound human confirmation.',
    inputSchema: PurgeWorkerEnvironmentRequestSchema.safeExtend(workspaceSelector),
    outputSchema: PurgeWorkerEnvironmentResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.configure',
    mutating: true,
  },
  'worker-environment.prepare': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Prepare an immutable Worker environment candidate without applying it.',
    inputSchema: WorkerEnvironmentPrepareInputSchema,
    outputSchema: PrepareWorkerEnvironmentResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'deployment' },
    policyOperation: 'api.call',
    mutating: true,
  },
  'worker-environment.recover': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description:
      'Recover an immutable Worker environment candidate without acquiring, building or applying an image.',
    inputSchema: WorkerEnvironmentRecoverInputSchema,
    outputSchema: PrepareWorkerEnvironmentResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'deployment' },
    policyOperation: 'api.call',
    mutating: true,
  },
  'worker-environment.activate': {
    binding: 'json',
    returnsOneTimeSecret: false,
    successStatus: 200,
    description: 'Activate an exact human-confirmed Worker environment candidate.',
    inputSchema: ActivateWorkerEnvironmentRequestSchema,
    outputSchema: ActivateWorkerEnvironmentResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'deployment' },
    policyOperation: 'api.call',
    mutating: true,
  },
} as const satisfies Record<string, OperationDefinition>;
