import { WorkspaceIdSchema } from '@openkit/protocol';
import { z } from 'zod';
import {
  AcceptWorkspaceInvitationRequestSchema,
  ChangeWorkspaceMemberAccessRequestSchema,
  CreateWorkspaceInvitationRequestSchema,
  DeclineWorkspaceInvitationRequestSchema,
  DeleteWorkspaceRequestSchema,
  DisableUserRequestSchema,
  DisableUserResponseSchema,
  LeaveWorkspaceRequestSchema,
  ListWorkspaceInvitationsResponseSchema,
  ListWorkspaceMembersResponseSchema,
  RecoverDeletedWorkspaceRequestSchema,
  RecoverDeletedWorkspaceResponseSchema,
  RecoverWorkspaceAccessRequestSchema,
  RemoveWorkspaceMemberRequestSchema,
  RevokeWorkspaceInvitationRequestSchema,
  TransferWorkspaceOwnershipRequestSchema,
  WorkspaceAccessRecoveryResponseSchema,
  WorkspaceDeletionResponseSchema,
  WorkspaceInvitationMutationResponseSchema,
  WorkspaceMemberMutationResponseSchema,
  WorkspaceOwnershipMutationResponseSchema,
} from './workspace-sharing.js';

/** Canonical Workspace lifecycle contracts; Core receipts, authority and deletion phases retain their existing owners. */
export const WORKSPACE_LIFECYCLE_OPERATION_DEFINITIONS = {
  'workspace.member-list': {
    description: "List the Workspace's current members.",
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceMembersResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'membership.manage',
    mutating: false,
  },
  'workspace.invitation-list': {
    description: 'List invitations for the Workspace.',
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: ListWorkspaceInvitationsResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'membership.manage',
    mutating: false,
  },
  'workspace.invitation-create': {
    description: 'Invite an existing canonical user to the Workspace.',
    inputSensitivity: 'secret stdin',
    inputSchema: CreateWorkspaceInvitationRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
    }),
    outputSchema: WorkspaceInvitationMutationResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'membership.manage',
    mutating: true,
    successStatus: 201,
  },
  'workspace.my-invitation-list': {
    description: 'List invitations addressed to the current user.',
    inputSchema: z.object({}).strict(),
    outputSchema: ListWorkspaceInvitationsResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'user' },
    target: { kind: 'user' },
    policyOperation: 'invitation.respond',
    mutating: false,
  },
  'workspace.my-invitation-accept': {
    description: 'Accept the addressed invitation for its invitee.',
    inputSchema: AcceptWorkspaceInvitationRequestSchema.safeExtend({
      invitationId: z.string().min(1),
    }),
    outputSchema: WorkspaceInvitationMutationResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'user' },
    target: { kind: 'invitation', field: 'invitationId' },
    policyOperation: 'invitation.respond',
    mutating: true,
    mutationTarget: { kind: 'invitation-workspace', field: 'invitationId' },
  },
  'workspace.my-invitation-decline': {
    description: 'Decline the addressed invitation for its invitee.',
    inputSchema: DeclineWorkspaceInvitationRequestSchema.safeExtend({
      invitationId: z.string().min(1),
    }),
    outputSchema: WorkspaceInvitationMutationResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'user' },
    target: { kind: 'invitation', field: 'invitationId' },
    policyOperation: 'invitation.respond',
    mutating: true,
    mutationTarget: { kind: 'invitation-workspace', field: 'invitationId' },
  },
  'workspace.invitation-revoke': {
    description: 'Revoke a pending Workspace invitation.',
    inputSchema: RevokeWorkspaceInvitationRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      invitationId: z.string().min(1),
    }),
    outputSchema: WorkspaceInvitationMutationResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-invitation', field: 'invitationId' },
    policyOperation: 'membership.manage',
    mutating: true,
  },
  'workspace.member-access-change': {
    description: "Change an existing member's Workspace access level.",
    inputSchema: ChangeWorkspaceMemberAccessRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      targetUserId: z.string().min(1),
    }),
    outputSchema: WorkspaceMemberMutationResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-member', field: 'targetUserId' },
    policyOperation: 'membership.manage',
    mutating: true,
  },
  'workspace.member-remove': {
    description: 'Remove a member from the Workspace.',
    inputSchema: RemoveWorkspaceMemberRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
      targetUserId: z.string().min(1),
    }),
    outputSchema: WorkspaceMemberMutationResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-member', field: 'targetUserId' },
    policyOperation: 'membership.manage',
    mutating: true,
  },
  'workspace.leave': {
    description: 'Leave the Workspace as the current user.',
    inputSchema: LeaveWorkspaceRequestSchema.safeExtend({ workspaceId: WorkspaceIdSchema }),
    outputSchema: WorkspaceMemberMutationResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'user' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.leave',
    mutating: true,
    mutationTarget: { kind: 'body-workspace', field: 'workspaceId' },
  },
  'workspace.ownership-transfer': {
    description: 'Transfer Workspace ownership to an active member.',
    inputSchema: TransferWorkspaceOwnershipRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
    }),
    outputSchema: WorkspaceOwnershipMutationResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace' },
    policyOperation: 'workspace.lifecycle',
    mutating: true,
  },
  'workspace.access-recovery-read': {
    description: "Read the Workspace's current access-recovery state.",
    inputSchema: z.object({ workspaceId: WorkspaceIdSchema }).strict(),
    outputSchema: WorkspaceAccessRecoveryResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'workspace' },
    policyOperation: 'deployment.recover',
    mutating: false,
  },
  'workspace.access-recover': {
    description: 'Recover Workspace access using current administrator authority.',
    inputSchema: RecoverWorkspaceAccessRequestSchema.safeExtend({ workspaceId: WorkspaceIdSchema }),
    outputSchema: WorkspaceAccessRecoveryResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'workspace' },
    policyOperation: 'deployment.recover',
    mutating: true,
    mutationTarget: { kind: 'body-workspace', field: 'workspaceId' },
  },
  'user.disable': {
    description: 'Disable a canonical user and revoke their live access.',
    inputSchema: DisableUserRequestSchema.safeExtend({ targetUserId: z.string().min(1) }),
    outputSchema: DisableUserResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'server' },
    target: { kind: 'user', field: 'targetUserId' },
    policyOperation: 'api.call',
    mutating: true,
  },
  'workspace.delete': {
    description: 'Delete the Workspace or resume the exact recorded deletion request.',
    inputSchema: DeleteWorkspaceRequestSchema.safeExtend({ workspaceId: WorkspaceIdSchema }),
    outputSchema: WorkspaceDeletionResponseSchema,
    credentials: ['local-user', 'user-session', 'user-bearer', 'deployment-administrator'],
    scope: { kind: 'body-workspace', field: 'workspaceId' },
    target: { kind: 'workspace-deletion' },
    policyOperation: 'workspace.lifecycle',
    mutating: true,
    successStatuses: [200, 202],
  },
  'workspace.deleted-recover': {
    description: 'Recover the deleted Workspace from its verified archive.',
    inputSchema: RecoverDeletedWorkspaceRequestSchema.safeExtend({
      workspaceId: WorkspaceIdSchema,
    }),
    outputSchema: RecoverDeletedWorkspaceResponseSchema,
    credentials: ['local-user', 'user-session', 'deployment-administrator'],
    scope: { kind: 'user' },
    target: { kind: 'deleted-workspace' },
    policyOperation: 'workspace.write',
    mutating: true,
  },
} as const;
