import type { ChildProcessWithoutNullStreams } from 'node:child_process';
import { createRequire } from 'node:module';

/** Generated schema document fields the adapter actually consults. */
interface SchemaFile {
  readonly definitions?: Readonly<
    Record<
      string,
      {
        readonly enum?: readonly string[];
        readonly oneOf?: readonly {
          readonly enum?: readonly string[];
          readonly properties?: { readonly type?: { readonly enum?: readonly string[] } };
        }[];
      }
    >
  >;
  readonly required?: readonly string[];
}

/** One JSON-RPC object on the App Server stdio stream. */
interface RpcMessage {
  readonly id?: number | string;
  readonly method?: string;
  readonly params?: unknown;
  readonly result?: unknown;
  readonly error?: { readonly message: string; readonly code: number };
}

/** Prefix retained from a native stream before redaction. The shared runner redacts again. */
export const CODEX_DIAGNOSTIC_MAX_BYTES = 16 * 1024;

const require = createRequire(import.meta.url);

/**
 * Loads one generated schema. These documents are the pin's type source for the methods below;
 * a missing consumed enum or required field fails closed instead of guessing a replacement.
 */
function loadSchema(relativePath: string): SchemaFile {
  return require(`@openkit/codex-app-server-schema/generated-schema/${relativePath}`) as SchemaFile;
}

/** Returns the string enum values of one schema definition, including oneOf branches. */
function schemaEnums(relativePath: string, definition: string): readonly string[] {
  const entry = loadSchema(relativePath).definitions?.[definition];
  return [...(entry?.enum ?? []), ...(entry?.oneOf ?? []).flatMap((item) => item.enum ?? [])];
}

/** Closed item discriminants generated by the pinned App Server binary. */
export function codexThreadItemTypes(): readonly string[] {
  return (
    loadSchema('v2/ItemCompletedNotification.json').definitions?.ThreadItem?.oneOf ?? []
  ).flatMap((item) => item.properties?.type?.enum ?? []);
}

/** Closed Turn statuses generated by the pinned App Server binary. */
export function codexTurnStatuses(): readonly string[] {
  return schemaEnums('v2/TurnCompletedNotification.json', 'TurnStatus');
}

const approvalPolicies = schemaEnums('v2/ThreadStartParams.json', 'AskForApproval');
const sandboxModes = schemaEnums('v2/ThreadStartParams.json', 'SandboxMode');
const commandDecisions = schemaEnums(
  'CommandExecutionRequestApprovalResponse.json',
  'CommandExecutionApprovalDecision'
);
const elicitationActions = schemaEnums(
  'McpServerElicitationRequestResponse.json',
  'McpServerElicitationAction'
);
const turnStartRequired = loadSchema('v2/TurnStartParams.json').required ?? [];

if (!approvalPolicies.includes('never') || !sandboxModes.includes('danger-full-access')) {
  throw new Error('Pinned Codex schema is missing the fail-closed approval or sandbox value.');
}
if (
  !commandDecisions.includes('accept') ||
  !commandDecisions.includes('cancel') ||
  !elicitationActions.includes('accept') ||
  !elicitationActions.includes('cancel')
) {
  throw new Error(
    'Pinned Codex schema is missing an allow-once or cancellation response for a native permission request.'
  );
}
if (!turnStartRequired.includes('threadId') || !turnStartRequired.includes('input')) {
  throw new Error('Pinned Codex schema no longer requires threadId and input on turn/start.');
}

/** Approval policy consumed from the generated AskForApproval enum. */
export const CODEX_APPROVAL_POLICY = 'never' as const;
/** Sandbox consumed from the generated SandboxMode enum. */
export const CODEX_SANDBOX = 'danger-full-access' as const;

/** Product-safe record of one answered native permission or question. */
export interface CodexPermissionRecord {
  readonly method: string;
  readonly outcome: 'accept' | 'cancel' | 'reject_once' | 'unsupported';
}

/** Answers unexpected native permissions with the pin's shortest-lived grant by default. */
export function codexPermissionResponse(
  method: string,
  params: unknown
): { readonly result: unknown; readonly outcome: CodexPermissionRecord['outcome'] } {
  if (!KNOWN_PERMISSION_METHODS.has(method)) return { result: null, outcome: 'unsupported' };
  const options = offeredOptions(params);
  // Retain refusal responses for future user-configurable policy; no policy setting is supplied yet.
  if (options.length > 0 && !options.includes('accept')) {
    if (options.includes('reject_once'))
      return { result: { decision: 'reject_once' }, outcome: 'reject_once' };
    if (method === 'mcpServer/elicitation/request')
      return { result: { action: 'cancel' }, outcome: 'cancel' };
    return { result: { decision: 'cancel' }, outcome: 'cancel' };
  }
  if (method === 'mcpServer/elicitation/request')
    return { result: { action: 'accept' }, outcome: 'accept' };
  if (method === 'item/permissions/requestApproval') {
    const permissions = (params as { permissions: unknown }).permissions;
    return { result: { permissions, scope: 'turn' }, outcome: 'accept' };
  }
  return { result: { decision: 'accept' }, outcome: 'accept' };
}

/** Reads a shallow `options` string list when a request offers explicit decisions. */
function offeredOptions(params: unknown): readonly string[] {
  if (!params || typeof params !== 'object' || !('options' in params)) return [];
  const options = (params as { options?: unknown }).options;
  if (!Array.isArray(options)) return [];
  return options.filter((option): option is string => typeof option === 'string');
}

/** Replaces known secret values and keeps a 16 KiB prefix of one diagnostic stream. */
export function redactDiagnostic(text: string, secrets: readonly string[]): string {
  let redacted = text;
  for (const secret of secrets) {
    if (secret) redacted = redacted.split(secret).join('[redacted]');
  }
  const bytes = Buffer.from(redacted, 'utf8');
  let end = Math.min(bytes.length, CODEX_DIAGNOSTIC_MAX_BYTES);
  while (end < bytes.length && end > 0 && (bytes[end]! & 0xc0) === 0x80) end -= 1;
  return bytes.subarray(0, end).toString('utf8');
}

/** Native request deadline; cleanup has a separate four-second allowance below the Harness budget. */
export const CODEX_RPC_TIMEOUT_MS = 4_000;
const KNOWN_PERMISSION_METHODS = new Set([
  'item/commandExecution/requestApproval',
  'item/fileChange/requestApproval',
  'item/permissions/requestApproval',
  'mcpServer/elicitation/request',
]);

/** Stdio JSON-RPC session for one `codex app-server` process. */
export class CodexAppServer {
  readonly permissionRecords: CodexPermissionRecord[] = [];
  private readonly pending = new Map<
    string,
    { resolve: (message: RpcMessage) => void; reject: (error: Error) => void }
  >();
  private readonly stderrDecoder = new TextDecoder('utf-8');
  private readonly decoder = new TextDecoder('utf-8', { fatal: true });
  private buffer = '';
  private stderrText = '';
  private stderrEnded = false;
  private nextId = 1;
  private outbound: Promise<void> = Promise.resolve();
  private broken = false;
  /** RPC unavailability does not discard buffered stdout behind process exit. */
  private stdoutBroken = false;
  private stdoutEnded = false;

  /**
   * @param child Supervised App Server process with piped stdio.
   * @param secrets Loopback credentials removed from any surfaced server error or stderr.
   * @param onNotification Server notifications, excluding requests that this class answers.
   * @param onBroken Invalid UTF-8 or an oversized frame. The caller fails the binding.
   */
  constructor(
    private readonly child: ChildProcessWithoutNullStreams,
    private readonly secrets: readonly string[],
    private readonly onNotification: (method: string, params: unknown) => void,
    private readonly onBroken: (reason: string) => void,
    private readonly controlTimeoutMs = CODEX_RPC_TIMEOUT_MS
  ) {
    child.stdout.on('data', (chunk: Buffer) => this.onStdout(chunk));
    child.stdout.on('end', () => this.endStdout());
    child.stdout.on('close', () => {
      if (!this.stdoutEnded) this.fail('Codex app-server stdout closed before EOF.');
    });
    child.stdout.on('error', () => this.fail('Codex app-server stdout failed.'));
    child.stderr.on('end', () => this.endStderr());
    child.stderr.on('close', () => this.endStderr());
    child.stderr.on('error', () => {
      this.endStderr();
      this.fail('Codex app-server stderr failed.');
    });
    child.stderr.on('data', (chunk: Buffer) => this.onStderr(chunk));
    child.stdin.on('error', () => this.fail('Codex app-server stdin failed.'));
    child.on('exit', () => this.fail('Codex app-server exited.', true));
    child.on('error', () => this.fail('Codex app-server failed to start.'));
  }

  /** Flushes the stderr decoder once across end, close, and error. */
  private endStderr(): void {
    if (this.stderrEnded) return;
    this.stderrEnded = true;
    this.stderrText = redactDiagnostic(this.stderrText + this.stderrDecoder.decode(), this.secrets);
  }

  /** Bounded stderr prefix for a failed Turn. Protocol stdout is never a diagnostic. */
  stderrDiagnostic(): string {
    return redactDiagnostic(this.stderrText, this.secrets);
  }

  /** Sends one request and resolves its result. The error text is redacted and not a thread id. */
  async request(
    method: string,
    params: unknown,
    timeoutMs = this.controlTimeoutMs
  ): Promise<unknown> {
    if (timeoutMs <= 0) throw new Error('Codex app-server control deadline expired.');
    if (this.broken) throw new Error('Codex app-server stream is unusable.');
    const id = this.nextId++;
    const abort = new AbortController();
    let timer: ReturnType<typeof setTimeout> | undefined;
    const response = new Promise<RpcMessage>((resolve, reject) => {
      this.pending.set(String(id), { resolve, reject });
    });
    const deadline = new Promise<never>((_, reject) => {
      timer = setTimeout(() => {
        abort.abort();
        reject(new Error(`Codex app-server timed out: ${method}`));
      }, timeoutMs);
    });
    try {
      const message = await Promise.race([
        Promise.all([this.send({ id, method, params }, abort.signal), response]).then(
          ([, message]) => message
        ),
        deadline,
      ]);
      if (message.error) {
        throw new Error(redactDiagnostic(message.error.message, this.secrets));
      }
      return message.result;
    } finally {
      clearTimeout(timer);
      this.pending.delete(String(id));
      abort.abort();
    }
  }

  /** Bounded handshake notification, including any outbound backpressure. */
  async notify(method: string, timeoutMs = this.controlTimeoutMs): Promise<void> {
    if (timeoutMs <= 0) throw new Error('Codex app-server control deadline expired.');
    const abort = new AbortController();
    const timer = setTimeout(() => abort.abort(), timeoutMs);
    try {
      await this.send({ method }, abort.signal);
    } finally {
      clearTimeout(timer);
      abort.abort();
    }
  }

  /** Flushes the decoder once; EOF is loss of terminal evidence even at a frame boundary. */
  private endStdout(): void {
    if (this.stdoutEnded) return;
    this.stdoutEnded = true;
    if (this.stdoutBroken) return;
    try {
      this.buffer += this.decoder.decode();
      this.fail(
        this.buffer.trim()
          ? 'Codex app-server stdout ended mid-frame.'
          : 'Codex app-server stdout ended.'
      );
    } catch {
      this.fail('Codex app-server stdout ended mid-UTF-8.');
    }
  }

  private onStdout(chunk: Buffer): void {
    if (this.stdoutBroken || this.stdoutEnded) return;
    let text: string;
    try {
      text = this.decoder.decode(chunk, { stream: true });
    } catch {
      this.fail('Codex app-server stdout is not UTF-8.');
      return;
    }
    this.buffer += text;
    if (Buffer.byteLength(this.buffer, 'utf8') > 32 * 1024 * 1024) {
      this.buffer = '';
      this.fail('Codex app-server frame exceeded the retained bound.');
      return;
    }
    let newline = this.buffer.indexOf('\n');
    while (newline >= 0) {
      const line = this.buffer.slice(0, newline);
      this.buffer = this.buffer.slice(newline + 1);
      if (line.trim()) {
        try {
          this.onLine(line);
        } catch {
          this.fail('Codex app-server frame is malformed.');
          return;
        }
      }
      if (this.stdoutBroken) return;
      newline = this.buffer.indexOf('\n');
    }
  }

  private onLine(line: string): void {
    let parsed: unknown;
    try {
      parsed = JSON.parse(line) as unknown;
    } catch {
      this.fail('Codex app-server frame is not JSON.');
      return;
    }
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('envelope');
    const message = parsed as RpcMessage;
    if (
      message.id !== undefined &&
      typeof message.id !== 'number' &&
      typeof message.id !== 'string'
    )
      throw new Error('id');
    if (message.method !== undefined && typeof message.method !== 'string')
      throw new Error('method');
    if (
      message.error !== undefined &&
      (!message.error ||
        typeof message.error !== 'object' ||
        Array.isArray(message.error) ||
        typeof message.error.message !== 'string' ||
        !Number.isSafeInteger(message.error.code))
    )
      throw new Error('error');
    if (message.method && message.id != null && message.result === undefined && !message.error) {
      this.answerRequest(message);
      return;
    }
    if (
      message.id != null &&
      (message.result !== undefined) !== (message.error !== undefined) &&
      !message.method
    ) {
      const pending = this.pending.get(String(message.id));
      this.pending.delete(String(message.id));
      pending?.resolve(message);
      return;
    }
    if (
      message.method &&
      message.id == null &&
      message.result === undefined &&
      message.error === undefined
    ) {
      this.onNotification(message.method, message.params);
      return;
    }
    throw new Error('shape');
  }

  private answerRequest(message: RpcMessage): void {
    const method = message.method ?? 'unknown';
    const decision = codexPermissionResponse(method, message.params);
    if (this.permissionRecords.length === 16) this.permissionRecords.shift();
    this.permissionRecords.push({
      method: KNOWN_PERMISSION_METHODS.has(method) ? method : 'unknown',
      outcome: decision.outcome,
    });
    if (decision.outcome === 'unsupported') {
      void this.send({
        id: message.id,
        error: { code: -32601, message: 'unsupported' },
      }).catch(() => this.fail('Codex permission response failed.'));
      this.fail('Codex native request has no proved cancellation.');
      return;
    }
    void this.send({ id: message.id, result: decision.result }).catch(() =>
      this.fail('Codex permission response failed.')
    );
  }

  private onStderr(chunk: Buffer): void {
    this.stderrText = redactDiagnostic(
      this.stderrText + this.stderrDecoder.decode(chunk, { stream: true }),
      this.secrets
    );
  }

  private send(payload: unknown, signal?: AbortSignal): Promise<void> {
    const ownedAbort = signal ? null : new AbortController();
    const timer = ownedAbort
      ? setTimeout(() => ownedAbort.abort(), this.controlTimeoutMs)
      : undefined;
    signal ??= ownedAbort?.signal;
    const run = this.outbound.then(() => this.writeLine(`${JSON.stringify(payload)}\n`, signal));
    this.outbound = run.then(
      () => undefined,
      () => undefined
    );
    return run.finally(() => clearTimeout(timer));
  }

  private writeLine(line: string, signal?: AbortSignal): Promise<void> {
    if (this.broken || signal?.aborted || this.child.stdin.destroyed)
      return Promise.reject(new Error('Codex app-server stream is unusable.'));
    return new Promise((resolve, reject) => {
      const cleanup = () => {
        this.child.stdin.off('error', failed);
        this.child.stdin.off('close', closed);
        this.child.stdin.off('drain', drained);
        signal?.removeEventListener('abort', closed);
      };
      const failed = () => {
        cleanup();
        reject(new Error('Codex app-server stdin failed.'));
      };
      const closed = () => {
        cleanup();
        reject(new Error('Codex app-server stdin closed.'));
      };
      const drained = () => {
        cleanup();
        resolve();
      };
      signal?.addEventListener('abort', closed, { once: true });
      this.child.stdin.once('error', failed);
      this.child.stdin.once('close', closed);
      try {
        if (this.child.stdin.write(line)) {
          cleanup();
          resolve();
        } else this.child.stdin.once('drain', drained);
      } catch {
        failed();
      }
    });
  }

  /** Closes RPCs independently of the stdout tail, whose later failures must still invalidate close. */
  private fail(reason: string, preserveStdout = false): void {
    const alreadyBroken = this.broken;
    if (alreadyBroken && this.stdoutBroken) return;
    if (!preserveStdout) this.stdoutBroken = true;
    this.broken = true;
    this.rejectPending(reason);
    if (!alreadyBroken || !preserveStdout) this.onBroken(reason);
  }

  private rejectPending(reason: string): void {
    for (const [id, pending] of this.pending) {
      this.pending.delete(id);
      pending.reject(new Error(reason));
    }
  }
}
